version: '3.9'

services:
  backend-app:
    container_name: event_management_backend_app
    image: event_management_backend_app
    ports:
      - 8000:8000
    command: wait-for-it db:5432 -- /bin/sh -c 
             "./manage.py collectstatic --no-input &&
             ./manage.py migrate &&
             ./manage.py runserver 0.0.0.0:8000"
            #  uwsgi --master --http :8000 --module core.project.wsgi" # run with main setting (without swagger)
    env_file:
      - ../.env
    links:
      - db