version: '3.9'


services:
  db:
    image: postgres:13-alpine
    container_name: django-event-management-db
    volumes:
      - django_event_management_db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ../.env
  
volumes:
  django_event_management_db:
