# Generated by Django 5.1 on 2024-09-02 13:03

import core.apps.common.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('title', models.CharField(max_length=255, verbose_name="Event's title")),
                ('description', models.TextField(blank=True, verbose_name="Event's description")),
                ('date', models.DateTimeField(verbose_name="Event's date")),
                ('adress', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Adress')),
                ('lat', core.apps.common.fields.CoordinateField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('lon', core.apps.common.fields.CoordinateField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Organizer of the event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
